import Image from "next/image";
import Link from "next/link";
import PublicPageShell from "@/components/PublicPageShell";
import { currentProductPrice, formatRand, getStoreProducts, isEquipment, isMembership, isSaleActive, isService, type StoreProduct } from "@/lib/storeCatalogue";

export const dynamic = "force-dynamic";
export default async function StorePage() {
  const products = await getStoreProducts();
  const equipment = products.filter(isEquipment);
  const services = products.filter(isService);
  const apparel = products.filter((product) => !isEquipment(product) && !isMembership(product) && !isService(product));
  return <PublicPageShell><main className="min-h-screen bg-white pt-[88px] text-slate-950">
    <div className="bg-slate-950 px-4 py-2.5 text-center text-[11px] font-bold uppercase tracking-[0.16em] text-white">Official PCC products · Pay securely online · Prices in ZAR</div>
    <section className="relative min-h-[72vh] overflow-hidden bg-[#ede9e1]"><div className="absolute inset-y-0 right-0 hidden w-[52%] bg-red-700 lg:block"/><div className="relative mx-auto grid min-h-[72vh] max-w-[1500px] lg:grid-cols-2"><div className="flex flex-col justify-center px-6 py-16 sm:px-10 lg:px-16"><p className="text-xs font-black uppercase tracking-[0.28em] text-red-700">Polokwane Chess Club Store</p><h1 className="mt-5 max-w-2xl text-5xl font-black uppercase leading-[0.9] tracking-[-0.055em] sm:text-7xl xl:text-8xl">Play ready.<br/>Club proud.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-600">Competition-ready chess equipment and official PCC apparel, selected for players, schools and clubs.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#shop" className="rounded-full bg-slate-950 px-7 py-3.5 text-sm font-black text-white hover:bg-red-700">Shop the collection</a><a href="#apparel" className="rounded-full border border-slate-950 px-7 py-3.5 text-sm font-black">Club apparel</a></div></div><div className="relative min-h-[460px] lg:min-h-0"><Image src="/images/store/pcc-tournament-jacket.png" alt="PCC Tournament Jacket" fill sizes="(min-width:1024px) 50vw,100vw" className="object-contain object-center p-6 lg:p-12" preload/></div></div></section>
    <section className="border-b border-slate-200 px-5 py-5"><div className="mx-auto grid max-w-7xl gap-4 sm:grid-cols-3"><Trust title="Secure online payments" text="PCC does not receive or keep your card details."/><Trust title="Club-managed stock" text="Availability and pricing are controlled by PCC."/><Trust title="Personal support" text="PCC confirms collection or delivery after ordering."/></div></section>
    <section className="px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Shop by collection" title="Find your game." text="Everything you need at the board, plus clubwear that represents PCC."/><div className="mt-9 grid gap-5 md:grid-cols-2"><CollectionCard href="#equipment" title="Tournament equipment" text="Boards and clocks for training, schools and rated competition." image={equipment.find((item)=>item.primary_image_url)?.primary_image_url||"/images/store/ps-1688-chess-clock.jpg"}/><CollectionCard href="#apparel" title="Official clubwear" text="PCC clothing designed for players, officials and supporters." image="/images/store/pcc-chess-pieces-polo.png" dark/></div></div></section>
    <section id="shop" className="scroll-mt-28 bg-[#f5f5f3] px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="The store" title="Tournament essentials" text="Straightforward equipment for the board, the clock and the competition hall."/><div id="equipment" className="mt-9 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{equipment.map((product)=><ProductCard key={product.id} product={product}/>)}</div></div></section>
    {services.length > 0 && <section id="services" className="scroll-mt-28 bg-slate-950 px-5 py-16 text-white sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Limited PCC services" title="Upgrade your player profile." text="Digital services that help PCC members present a complete and recognisable player profile." light/><div className="mt-9 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{services.map((product)=><ProductCard key={product.id} product={product}/>)}</div></div></section>}
    <section id="apparel" className="scroll-mt-28 px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Represent PCC" title="Official club apparel" text="Clean, recognisable clubwear for tournaments, travel and everyday chess."/><div className="mt-9 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{apparel.map((product)=><ProductCard key={product.id} product={product}/>)}</div></div></section>
    <section className="bg-red-700 px-5 py-16 text-white sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-red-100">PCC service</p><h2 className="mt-3 text-4xl font-black tracking-tight">Need help before you order?</h2><p className="mt-3 max-w-2xl leading-7 text-red-100">Ask about equipment, school quantities, sizing, collection or delivery. You speak directly to the club.</p></div><Link href="/contact" className="rounded-full bg-white px-7 py-3.5 text-center text-sm font-black text-slate-950">Contact PCC</Link></div></section>
  </main></PublicPageShell>;
}

function ProductCard({ product }: { product: StoreProduct }) { const sale=isSaleActive(product); const available=product.stock_status==="available"; return <article className="group overflow-hidden border border-slate-200 bg-white text-slate-950 shadow-[0_8px_30px_rgba(15,23,42,0.05)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_16px_40px_rgba(15,23,42,0.10)]"><Link href={`/store/${product.slug}`} className="block"><div className="relative aspect-square overflow-hidden bg-white">{product.primary_image_url?<Image src={product.primary_image_url} alt={product.name} fill sizes="(min-width:1024px) 25vw,(min-width:640px) 50vw,100vw" className="object-contain p-3 transition duration-500 group-hover:scale-[1.035]"/>:<Placeholder category={product.category}/>}<div className="absolute left-3 top-3 flex gap-2">{sale&&<span className="bg-red-700 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-white">{product.sale_label||"Special"}</span>}{!available&&<span className="bg-slate-950 px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-white">{product.stock_status==="coming-soon"?"Coming soon":"Sold out"}</span>}</div></div><div className="border-t border-slate-100 p-5"><p className="text-xs font-bold text-slate-500">{product.category}{product.colour?` · ${product.colour}`:""}</p><h3 className="mt-1 text-lg font-black tracking-tight group-hover:underline">{product.name}</h3><div className="mt-2 flex items-baseline gap-2"><span className={sale?"font-black text-red-700":"font-black"}>{formatRand(currentProductPrice(product))}</span>{sale&&<span className="text-sm text-slate-400 line-through">{formatRand(product.regular_price)}</span>}</div></div></Link></article> }
function CollectionCard({href,title,text,image,dark=false}:{href:string;title:string;text:string;image:string;dark?:boolean}) { return <a href={href} className={`group grid min-h-[430px] overflow-hidden ${dark?"bg-slate-950 text-white":"bg-[#ede9e1]"}`}><div className="relative row-start-1 min-h-[280px]"><Image src={image} alt="" fill sizes="(min-width:768px) 50vw,100vw" className="object-contain p-5 transition duration-500 group-hover:scale-[1.03]"/></div><div className="row-start-2 p-7"><h3 className="text-3xl font-black tracking-tight">{title}</h3><p className={`mt-2 max-w-lg text-sm leading-6 ${dark?"text-slate-300":"text-slate-600"}`}>{text}</p><span className="mt-5 inline-block border-b border-current pb-1 text-sm font-black">Shop collection</span></div></a> }
function SectionHeading({eyebrow,title,text,light=false}:{eyebrow:string;title:string;text:string;light?:boolean}) { return <div><p className={`text-xs font-black uppercase tracking-[0.22em] ${light?"text-red-300":"text-red-700"}`}>{eyebrow}</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">{title}</h2><p className={`mt-3 max-w-2xl leading-7 ${light?"text-slate-300":"text-slate-600"}`}>{text}</p></div> }
function Trust({title,text}:{title:string;text:string}) { return <div className="py-2"><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div> }
function Placeholder({category}:{category:string}) { return <div className="flex h-full flex-col items-center justify-center bg-gradient-to-br from-white to-slate-100"><span className="text-7xl" aria-hidden="true">{category.toLowerCase().includes("board")?"♟":"⏱"}</span><p className="mt-4 text-xs font-black uppercase tracking-widest text-slate-400">Image coming soon</p></div> }
