-- Deprecated.
-- Do not use this older repair script.
--
-- Use these instead:
-- 1. database/admin_access_rebuild.sql
-- 2. database/admin_access_super_admin_repair.sql
--
-- The old version of this file treated admin_users as super-admin ownership.
-- That was too broad because admin_users is now only a compatibility whitelist.
