"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AdminGuard from "@/components/AdminGuard";
import { supabase } from "@/lib/supabase";

type OrderItem={id:string;product_name:string;unit_price:number;quantity:number;selected_option:string|null;line_total:number};
type StoreOrder={id:string;order_number:string;product_name:string;total_amount:number;currency:string;customer_name:string;customer_email:string;customer_phone:string;status:string;yoco_mode:string|null;yoco_payment_id:string|null;paid_at:string|null;created_at:string;fulfillment_method:string;delivery_address:string|null;delivery_fee:number;fulfillment_status:string;fulfillment_notes:string|null;store_order_items:OrderItem[]|null};

const statuses=["all","paid","payment_pending","failed","cancelled"] as const;

function money(value:number){return new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(Number(value))}
function date(value:string|null){return value?new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Not recorded"}
function tone(status:string){if(status==="paid")return "bg-emerald-500/15 text-emerald-300";if(status==="payment_pending")return "bg-amber-500/15 text-amber-200";if(status==="failed"||status==="cancelled")return "bg-red-500/15 text-red-200";return "bg-zinc-700 text-zinc-200"}

export default function StoreOrdersPage(){
  const [orders,setOrders]=useState<StoreOrder[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [filter,setFilter]=useState<(typeof statuses)[number]>("all");const [search,setSearch]=useState("");
  const load=useCallback(async()=>{setLoading(true);setMessage("");const {data,error}=await supabase.from("store_orders").select("id,order_number,product_name,total_amount,currency,customer_name,customer_email,customer_phone,status,yoco_mode,yoco_payment_id,paid_at,created_at,fulfillment_method,delivery_address,delivery_fee,fulfillment_status,fulfillment_notes,store_order_items(id,product_name,unit_price,quantity,selected_option,line_total)").order("created_at",{ascending:false}).limit(500);if(error)setMessage(`Could not load store orders: ${error.message}`);setOrders((data??[]) as StoreOrder[]);setLoading(false)},[]);
  async function updateFulfillment(id:string,status:string){const notes=window.prompt("Optional fulfilment note (visible to admins):",orders.find(order=>order.id===id)?.fulfillment_notes??"");if(notes===null)return;const {error}=await supabase.from("store_orders").update({fulfillment_status:status,fulfillment_notes:notes.trim()||null}).eq("id",id);if(error)setMessage(error.message);else await load()}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const visible=useMemo(()=>{const q=search.trim().toLowerCase();return orders.filter(order=>(filter==="all"||order.status===filter)&&(!q||[order.order_number,order.product_name,order.customer_name,order.customer_email,order.customer_phone].some(value=>value.toLowerCase().includes(q))))},[orders,filter,search]);
  const counts=useMemo(()=>({paid:orders.filter(x=>x.status==="paid"&&x.yoco_mode==="live").length,test:orders.filter(x=>x.status==="paid"&&x.yoco_mode==="test").length,pending:orders.filter(x=>x.status==="payment_pending").length,total:orders.reduce((sum,x)=>sum+(x.status==="paid"&&x.yoco_mode==="live"?Number(x.total_amount):0),0)}),[orders]);
  return <AdminGuard><main className="min-h-screen bg-zinc-950 px-5 pb-20 pt-28 text-white"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-red-300">PCC Store</p><h1 className="mt-3 text-4xl font-black">Store orders</h1><p className="mt-3 max-w-3xl text-zinc-400">See every online product and service order, payment confirmation and customer contact detail.</p></div><div className="flex gap-3"><button onClick={()=>void load()} className="rounded-xl border border-white/15 px-4 py-3 text-sm font-black">Refresh</button><Link href="/admin/store-products" className="rounded-xl bg-white px-4 py-3 text-sm font-black text-zinc-950">Manage products</Link></div></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Live paid orders" value={`${counts.paid}`}/><Stat label="Awaiting confirmation" value={`${counts.pending}`}/><Stat label="Live confirmed revenue" value={money(counts.total)}/><Stat label="Test payments" value={`${counts.test}`}/></section>
    <section className="mt-6 rounded-2xl border border-white/10 bg-zinc-900 p-5"><div className="grid gap-4 md:grid-cols-[1fr_auto]"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, customer, email or phone" className="rounded-xl border border-white/10 bg-black px-4 py-3 text-sm"/><div className="flex flex-wrap gap-2">{statuses.map(status=><button key={status} onClick={()=>setFilter(status)} className={`rounded-full px-4 py-2 text-xs font-black capitalize ${filter===status?"bg-red-700 text-white":"bg-white/5 text-zinc-300"}`}>{status.replace("_"," ")}</button>)}</div></div></section>
    {message&&<p className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{message}</p>}
    {loading?<p className="mt-8 text-zinc-400">Loading store orders…</p>:visible.length===0?<p className="mt-8 rounded-2xl border border-white/10 bg-zinc-900 p-6 text-zinc-400">No store orders match this view.</p>:<div className="mt-6 space-y-4">{visible.map(order=><article key={order.id} className="rounded-2xl border border-white/10 bg-zinc-900 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-black">{order.order_number}</h2><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${tone(order.status)}`}>{order.status.replace("_"," ")}</span>{order.yoco_mode&&<span className="rounded-full bg-white/5 px-3 py-1 text-xs font-bold uppercase text-zinc-400">{order.yoco_mode}</span>}</div><p className="mt-2 text-sm text-zinc-400">Ordered {date(order.created_at)} · Paid {date(order.paid_at)}</p></div><p className="text-2xl font-black text-emerald-300">{money(order.total_amount)}</p></div>
      <div className="mt-5 grid gap-5 border-t border-white/10 pt-5 md:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-wide text-zinc-500">Customer</p><p className="mt-2 font-black">{order.customer_name}</p><div className="mt-2 flex flex-wrap gap-3 text-sm"><a href={`mailto:${order.customer_email}`} className="text-blue-300 underline">{order.customer_email}</a><a href={`https://wa.me/${order.customer_phone.replace(/\D/g,"").replace(/^0/,"27")}`} target="_blank" rel="noreferrer" className="text-emerald-300 underline">{order.customer_phone}</a></div></div><div><p className="text-xs font-black uppercase tracking-wide text-zinc-500">Items</p><div className="mt-2 space-y-2">{order.store_order_items?.length?order.store_order_items.map(item=><div key={item.id} className="flex justify-between gap-4 text-sm"><span>{item.product_name}{item.selected_option?` · ${item.selected_option}`:""} × {item.quantity}</span><strong>{money(item.line_total)}</strong></div>):<div className="flex justify-between gap-4 text-sm"><span>{order.product_name}</span><strong>{money(order.total_amount)}</strong></div>}</div></div></div>
      <div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs font-black uppercase tracking-wide text-zinc-500">Fulfilment</p><p className="mt-2 text-sm font-bold">{order.fulfillment_method.replaceAll("_"," ")} · {money(order.delivery_fee||0)} · {order.fulfillment_status.replaceAll("_"," ")}</p>{order.delivery_address&&<p className="mt-2 text-sm text-zinc-300">{order.delivery_address}</p>}{order.fulfillment_notes&&<p className="mt-2 text-xs text-zinc-400">{order.fulfillment_notes}</p>}{order.status==="paid"&&<div className="mt-3 flex flex-wrap gap-2">{["preparing","ready_for_collection","dispatched","completed","refunded"].map(status=><button key={status} type="button" onClick={()=>void updateFulfillment(order.id,status)} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-bold capitalize">{status.replaceAll("_"," ")}</button>)}</div>}</div>
      {order.yoco_payment_id&&<p className="mt-4 text-xs text-zinc-500">Payment confirmation: {order.yoco_payment_id}</p>}
    </article>)}</div>}
  </div></main></AdminGuard>
}

function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-zinc-900 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-zinc-500">{label}</p><p className="mt-3 text-3xl font-black">{value}</p></div>}
